# -*- coding: utf-8 -*-
"""mlops2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xk-e4eBBDJa6bvhoFkWIlm8JoCCiM1m
"""

!cd /content
!mkdir -p mlops_project/src
!mkdir -p mlops_project/data/raw
!mkdir -p mlops_project/models
!mkdir -p mlops_project/metrics
!mkdir -p mlops_project/reports

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/mlops_project/Makefile
# 
# install:
# 	@echo "Installing dependencies..."
# 	pip install -q seaborn scikit-learn pandas dvc

!cd /content/mlops_project
!make install

!cd /content/mlops_project
!ls -la

!cd /content/mlops_project
!ls -la

!cd /content
!mkdir -p mlops_project/src
!mkdir -p mlops_project/data/raw
!mkdir -p mlops_project/data/processed
!mkdir -p mlops_project/models
!mkdir -p mlops_project/metrics
!mkdir -p mlops_project/reports
!cd /content/mlops_project

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/mlops_project/Makefile
# 
# .PHONY: install
# 
# install:
# 	@echo "Installing dependencies..."
# 	pip install -q seaborn scikit-learn pandas dvc

!make install

!cd /content/mlops_project
!ls -la

!cd /content/mlops_project
!ls -la
!cat Makefile

!pwd
!ls -la

!cd /content/mlops_project

!pwd

!cd mlops_project

!ls -ld mlops_project

!chmod +rx mlops_project

!cd mlops_project

!pwd

# Commented out IPython magic to ensure Python compatibility.
# %cd mlops_project

!ls -la

!make install

!git init
!dvc init
!mkdir -p .dvcstore
!dvc remote add -d local ./.dvcstore

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/get_data.py
# import seaborn as sns
# 
# tips = sns.load_dataset("tips")
# tips.to_csv("data/raw/tips.csv", index=False)
# print("Saved data/raw/tips.csv")

!python src/get_data.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/preprocess.py
# import pandas as pd
# 
# df = pd.read_csv("data/raw/tips.csv")
# df["high_tip"] = (df["tip"] > df["tip"].median()).astype(int)
# df.to_csv("data/processed/tips_processed.csv", index=False)
# print("Saved data/processed/tips_processed.csv")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/train.py
# import pandas as pd
# import joblib
# from sklearn.linear_model import LogisticRegression
# 
# df = pd.read_csv("data/processed/tips_processed.csv")
# X = df[["total_bill", "size"]]
# y = df["high_tip"]
# 
# model = LogisticRegression(max_iter=1000)
# model.fit(X, y)
# joblib.dump(model, "models/logreg.pkl")
# print("Saved models/logreg.pkl")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/evaluate.py
# import pandas as pd
# import joblib
# from sklearn.metrics import accuracy_score
# 
# df = pd.read_csv("data/processed/tips_processed.csv")
# X = df[["total_bill", "size"]]
# y = df["high_tip"]
# 
# model = joblib.load("models/logreg.pkl")
# pred = model.predict(X)
# acc = accuracy_score(y, pred)
# 
# print(f"accuracy: {acc:.4f}")
# 
# with open("metrics/accuracy.json", "w") as f:
#     f.write(f'{{"accuracy": {acc:.4f}}}')

!dvc stage add -n get_data -o data/raw/tips.csv python src/get_data.py
!dvc stage add -n preprocess -d data/raw/tips.csv -o data/processed/tips_processed.csv python src/preprocess.py
!dvc stage add -n train -d data/processed/tips_processed.csv -o models/logreg.pkl python src/train.py
!dvc stage add -n evaluate -d data/processed/tips_processed.csv -d models/logreg.pkl -M metrics/accuracy.json python src/evaluate.py

!git add data/raw/.gitignore data/processed/.gitignore models/.gitignore dvc.yaml
!git commit -m "Add DVC pipeline stages"

!git config --global user.name "credibility-index"
!git config --global user.email "nothetal@gmail.com"

!git add data/raw/.gitignore data/processed/.gitignore models/.gitignore dvc.yaml
!git commit -m "Add DVC pipeline stages"

!git config --global --list

!git add data/raw/.gitignore data/processed/.gitignore models/.gitignore dvc.yaml
!git commit -m "Add DVC pipeline stages"

!dvc repro
!dvc push

!git add dvc.lock dvc.yaml .dvc/config Makefile src/
!git commit -m "Complete DVC ML pipeline"

ls -la

!find /content -name dvc.yaml -o -name Makefile -o -name LICENSE -o -name .gitignore

!git status

from operator import getitem
!git remote add origin https://github.com/credibility-index/mlops_2015.get
!git branch -M main
!git push -u origin main

!git remote -v

!git remote set-url origin https://github.com/credibility-index/mlops_2015.git
!git remote -v

!git push -u origin master

!git remote set-url origin https://github.com/credibility-index/mlops_2015.git
!git branch -M main
!git add .
!git commit -m "Initial project upload"
!git push -u origin main

!git branch